# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9649ea5087ca7b4f4314088f4de49b4247142b4d8434a83d3f2882bc8d11e8ad9ac573ee920fd40ee3cd863283cf7b4a566af6fa2cd9e8b4a3c9cf8101114edc

test:
  secret_key_base: f9ee8090d3d6ed5ee5f8b473b1f7b4c34b83e2050030298fdd83b79eb9d8087e6ea6da19a261638c700119d1388b8d815c54955fb1c1fcc2b3f45cadc8239b0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
